# Example 002
extend = [
    { path = "vulkan.toml" },
    { path = "metal.toml" },
    { path = "dx12.toml" },
    { path = "dx11.toml" },
    { path = "opengl.toml" },
    { path = "browser_webgpu.toml" },
]

[tasks.build-example-002-all]
category = "build"
dependencies = [
    "build-example-002-vulkan",
    "build-example-002-metal",
    "build-example-002-dx12",
    "build-example-002-dx11",
    "build-example-002-opengl",
    "build-example-002-browser_webgpu",
]

[tasks.release-build-example-002-all]
category = "release-build"
dependencies = [
    "release-build-example-002-vulkan",
    "release-build-example-002-metal",
    "release-build-example-002-dx12",
    "release-build-example-002-dx11",
    "release-build-example-002-opengl",
    "release-build-example-002-browser_webgpu",
]
