# Example 002 - Metal
[tasks.cargo_build-example-002-metal]
command = "cargo"
args = ["build", "--example=002_window_init", "--features=gl_metal"]

[tasks.windows_build-example-002-metal]
command = "cp"
args = [
    "target/debug/examples/002_window_init.exe",
    "target/debug/examples/002_window_init_metal.exe",
]
dependencies = ["cargo_build-example-002-metal"]

[tasks.non-windows_build-example-002-metal]
command = "cp"
args = [
    "target/debug/examples/002_window_init",
    "target/debug/examples/002_window_init_metal",
]
dependencies = ["cargo_build-example-002-metal"]

[tasks.build-example-002-metal]
category = "build"
windows_alias = "windows_build-example-002-metal"
linux_alias = "non-windows_build-example-002-metal"
mac_alias = "non-windows_build-example-002-metal"

[tasks.run-example-002-metal]
category = "run"
command = "cargo"
args = ["run", "--example=002_window_init", "--features=gl_metal"]
dependencies = ["cargo_build-example-002-metal"]

# --- Release ---
[tasks.release-cargo_build-example-002-metal]
command = "cargo"
args = ["build", "--example=002_window_init", "--features=gl_metal"]

[tasks.release-windows_build-example-002-metal]
command = "cp"
args = [
    "target/release/examples/002_window_init.exe",
    "target/release/examples/002_window_init_metal.exe",
]
dependencies = ["release-cargo_build-example-002-metal"]

[tasks.release-non-windows_build-example-002-metal]
command = "cp"
args = [
    "target/release/examples/002_window_init",
    "target/release/examples/002_window_init_metal",
]
dependencies = ["release-cargo_build-example-002-metal"]

[tasks.release-build-example-002-metal]
category = "release-build"
windows_alias = "windows_build-example-002-metal"
linux_alias = "non-windows_build-example-002-metal"
mac_alias = "non-windows_build-example-002-metal"

[tasks.release-run-example-002-metal]
category = "release-run"
command = "cargo"
args = ["run", "--release", "--example=002_window_init", "--features=gl_metal"]
dependencies = ["release-cargo_build-example-002-metal"]
