[package]
name = "hello_compute"
version = "0.1.0"
edition = "2021"

[dependencies]
akimo_runtime = { path = "../../Runtime/" }

log = "0.4.21"
winit = "0.29.15"
wgpu = "0.19.3"
bytemuck = "1.15.0"
flume = "0.11.0"
