[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"

[dependencies]
akimo_runtime = { path = "../../Runtime/" }

log = "0.4.21"
winit = "0.29.15"
wgpu = "0.19.3"
flume = "0.11.0"
png = "0.17.13"
