[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"

[dependencies]
akimo_runtime = { workspace = true }

log = { workspace = true }
winit = { workspace = true }
wgpu = { workspace = true }
flume = { workspace = true }
png = { workspace = true }
