# Operating systems to run on
os:
  - osx
  - linux
  - windows

# What tools should be present
compiler:
  - gcc
  - clang

# Programming language
language: rust

# Version and channel of rust
rust:
  - stable

# Use a cache for cargo
cache: cargo

# Tasks
script:
  - cargo check --verbose --package shared
  - cargo build --verbose --package shared
  - cargo test --verbose --package shared
  - cargo check --verbose --package platform_${TRAVIS_OS_NAME}
  - cargo build --verbose --package platform_${TRAVIS_OS_NAME}
  - cargo test --verbose --package platform_${TRAVIS_OS_NAME}
  - cargo check --release --verbose --package shared
  - cargo build --release --verbose --package shared
  - cargo test --release --verbose --package shared
  - cargo check --release --verbose --package platform_${TRAVIS_OS_NAME}
  - cargo build --release --verbose --package platform_${TRAVIS_OS_NAME}
  - cargo test --release--verbose --package platform_${TRAVIS_OS_NAME}

# There is no easy way of building iOS and Android without requiring the Android SDK and iOS SDK on all platforms.
# Docker could be used here, but a more advanced setup is required which would just clutter this config.
