stages:
  - stage: Linux
    pool: 
      vmImage: ubuntu-latest
    jobs:
      - job: Install-Rust
        steps:
          - bash: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --profile complete -y
            displayName: Install Rust
          
          - bash: rustc --version && cargo --version
            displayName: Print Rust & Cargo versions
      
      - job: Cargo-Check-Debug
        dependsOn: Install-Rust
        steps:
          - bash: cargo check --verbose --package platform_linux
            displayName: Cargo Check (Debug)

      - job: Cargo-Check-Release
        dependsOn: Install-Rust
        steps:
          - bash: cargo check --verbose --package platform_linux --release
            displayName: Cargo Check (Release)

      - job: Cargo-Build-Debug
        dependsOn: Install-Rust
        steps:
          - bash: cargo build --verbose --package platform_linux
            displayName: Cargo Build (Debug)

      - job: Cargo-Build-Release
        dependsOn: Install-Rust
        steps:
          - bash: cargo build --verbose --package platform_linux --release
            displayName: Cargo Build (Release)

      - job: Cargo-Test-Debug
        dependsOn: Install-Rust
        steps:
          - bash: cargo test --verbose --package platform_linux
            displayName: Cargo Test (Debug)

      - job: Cargo-Test-Release
        dependsOn: Install-Rust
        steps:
          - bash: cargo test --verbose --package platform_linux --release
            displayName: Cargo Test (Release)

  - stage: Windows
    pool: 
      vmImage: windows-latest
    jobs:
      - job: Install-Rust
        steps:
          - pwsh: Invoke-WebRequest https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe -OutFile rustup-init.exe
            displayName: Download Rustup

          - pwsh: ./rustup-init.exe --default-toolchain stable --profile complete -y
            displayName: Install Rust
          
          - pwsh: rustc --version && cargo --version
            displayName: Print Rust & Cargo versions
      
      - job: Cargo-Check-Debug
        dependsOn: Install-Rust
        steps:
          - pwsh: cargo check --verbose --package platform_windows
            displayName: Cargo Check (Debug)

      - job: Cargo-Check-Release
        dependsOn: Install-Rust
        steps:
          - pwsh: cargo check --verbose --package platform_windows --release
            displayName: Cargo Check (Release)

      - job: Cargo-Build-Debug
        dependsOn: Install-Rust
        steps:
          - pwsh: cargo build --verbose --package platform_windows
            displayName: Cargo Build (Debug)

      - job: Cargo-Build-Release
        dependsOn: Install-Rust
        steps:
          - pwsh: cargo build --verbose --package platform_windows --release
            displayName: Cargo Build (Release)

      - job: Cargo-Test-Debug
        dependsOn: Install-Rust
        steps:
          - pwsh: cargo test --verbose --package platform_windows
            displayName: Cargo Test (Debug)

      - job: Cargo-Test-Release
        dependsOn: Install-Rust
        steps:
          - pwsh: cargo test --verbose --package platform_windows --release
            displayName: Cargo Test (Release)
