pool:
  vmImage: ubuntu-latest

steps:
- script: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --profile complete -y
  displayName: Install Rust

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    rustct --version && cargo --version  # Print version info for debugging
    cargo check --verbose --package platform_linux
  displayName: check

- script: |
    rustct --version && cargo --version  # Print version info for debugging
    cargo build --verbose --package platform_linux
  displayName: build

- script: |
    rustct --version && cargo --version  # Print version info for debugging
    cargo test --verbose --package platform_linux
  displayName: test
