stages:
  - stage: Linux
    pool: 
      vmImage: ubuntu-latest
    jobs:
      - job: Install_Rust
        steps:
          - script: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --profile complete -y
            displayName: Install Rust
          
          - script: rustc --version && cargo --version
            displayName: Print Rust & Cargo versions
      
      - job: Cargo_Check
        steps:
          - script: cargo check --verbose --package platform_linux
            displayName: Cargo Check

      - job: Cargo_Build
        steps:
          - script: cargo build --verbose --package platform_linux
            displayName: build

      - job: Cargo_Test
        steps:
          - script: cargo test --verbose --package platform_linux
            displayName: test
