[workspace]
resolver = "2"
members = ["Orbital/", "Example/"]

[profile.dev.package."*"]
opt-level = 3
debug = false
strip = true

[profile.dev]
opt-level = 1
debug = true
strip = false

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false
panic = "abort"
strip = true
