[workspace]
resolver = "2"
members = ["Runtime/", "Engine/", "Examples/*"]

[workspace.dependencies]
akimo_runtime = { path = "./Runtime/" }

winit = "0.29.14"
wgpu = "0.19.3"
log = "0.4.21"
fern = "0.6.2"
serde = "1.0.174"
serde_json = "1.0.103"
serde_derive = "1.0.174"
ulid = "1.1.2"
hashbrown = "0.14.3"
humantime = "2.1.0"
pollster = "0.3.0"
android_logger = "0.13.3"
image = "0.25.0"
flume = "0.11.0"
bytemuck = "1.15.0"
png = "0.17.13"
