[package]
name = "example_clear_screen"
version = "0.1.0"
edition = "2021"

[lib]
name = "app_example_clear_screen"
crate-type = ["cdylib", "lib"]

[dependencies]
akimo_runtime = { path = "../../Runtime/" }
