[package]
name = "asset_loading"
version = "0.1.0"
edition = "2021"

[lib]
name = "app_example_asset_loading"
crate-type = ["cdylib", "lib"]

[dependencies]
akimo_runtime = { path = "../../Runtime/" }
image = "0.25.1"
