[package]
name = "akimo_runtime"
version = "0.1.0"
edition = "2021"

[features]
default = ["engine"]
engine = []
include_examples = []
example_clear_screen = ["include_examples"]
example_triangle = ["include_examples"]

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
winit = { version = "0.29.14" }
wgpu = { version = "0.19.3", features = ["spirv", "glsl", "wgsl", "naga-ir"] }
log = "0.4.21"
fern = "0.6.2"
serde = { version = "1.0.174", features = ["derive"] }
serde_json = "1.0.103"
serde_derive = "1.0.174"
ulid = "1.1.2"
hashbrown = "0.14.3"
humantime = "2.1.0"
pollster = "0.3.0"

[dev-dependencies]
image = "0.25.0"
flume = "0.11.0"
bytemuck = "1.15.0"
png = "0.17.13"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13.3"
winit = { version = "0.29.15", features = ["android-native-activity"] }
