version: 2.1
jobs:
  platform_linux:
    docker:
      - image: cimg/rust:1.61
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Build (debug)
          command: cargo build --package platform_linux
      - run:
          name: Build (release)
          command: cargo build --package platform_linux --release
      - run:
          name: Run Tests (debug)
          command: cargo test --package platform_linux
      - run:
          name: Run Tests (release)
          command: cargo test --package platform_linux --release
      - store_artifacts:
        path: target/
