# Example 001 - Browser WebGPU
[tasks.cargo_build-example-001-browser_webgpu]
command = "cargo"
args = ["build", "--example=001_engine_init", "--features=gl_browser_webgpu"]

[tasks.windows_build-example-001-browser_webgpu]
command = "cp"
args = [
    "target/debug/examples/001_engine_init.exe",
    "target/debug/examples/001_engine_init_browser_webgpu.exe",
]
dependencies = ["cargo_build-example-001-browser_webgpu"]

[tasks.non-windows_build-example-001-browser_webgpu]
command = "cp"
args = [
    "target/debug/examples/001_engine_init",
    "target/debug/examples/001_engine_init_browser_webgpu",
]
dependencies = ["cargo_build-example-001-browser_webgpu"]

[tasks.build-example-001-browser_webgpu]
category = "build"
windows_alias = "windows_build-example-001-browser_webgpu"
linux_alias = "non-windows_build-example-001-browser_webgpu"
mac_alias = "non-windows_build-example-001-browser_webgpu"

[tasks.run-example-001-browser_webgpu]
category = "run"
command = "cargo"
args = ["run", "--example=001_engine_init", "--features=gl_browser_webgpu"]
dependencies = ["cargo_build-example-001-browser_webgpu"]

# --- Release ---
[tasks.release-cargo_build-example-001-browser_webgpu]
command = "cargo"
args = ["build", "--example=001_engine_init", "--features=gl_browser_webgpu"]

[tasks.release-windows_build-example-001-browser_webgpu]
command = "cp"
args = [
    "target/release/examples/001_engine_init.exe",
    "target/release/examples/001_engine_init_browser_webgpu.exe",
]
dependencies = ["release-cargo_build-example-001-browser_webgpu"]

[tasks.release-non-windows_build-example-001-browser_webgpu]
command = "cp"
args = [
    "target/release/examples/001_engine_init",
    "target/release/examples/001_engine_init_browser_webgpu",
]
dependencies = ["release-cargo_build-example-001-browser_webgpu"]

[tasks.release-build-example-001-browser_webgpu]
category = "release-build"
windows_alias = "windows_build-example-001-browser_webgpu"
linux_alias = "non-windows_build-example-001-browser_webgpu"
mac_alias = "non-windows_build-example-001-browser_webgpu"

[tasks.release-run-example-001-browser_webgpu]
category = "release-run"
command = "cargo"
args = [
    "run",
    "--release",
    "--example=001_engine_init",
    "--features=gl_browser_webgpu",
]
dependencies = ["release-cargo_build-example-001-browser_webgpu"]
