# Example 001 - DX12
[tasks.cargo_build-example-001-dx12]
command = "cargo"
args = ["build", "--example=001_engine_init", "--features=gl_dx12"]

[tasks.windows_build-example-001-dx12]
command = "cp"
args = [
    "target/debug/examples/001_engine_init.exe",
    "target/debug/examples/001_engine_init_dx12.exe",
]
dependencies = ["cargo_build-example-001-dx12"]

[tasks.non-windows_build-example-001-dx12]
command = "cp"
args = [
    "target/debug/examples/001_engine_init",
    "target/debug/examples/001_engine_init_dx12",
]
dependencies = ["cargo_build-example-001-dx12"]

[tasks.build-example-001-dx12]
category = "build"
windows_alias = "windows_build-example-001-dx12"
linux_alias = "non-windows_build-example-001-dx12"
mac_alias = "non-windows_build-example-001-dx12"

[tasks.run-example-001-dx12]
category = "run"
command = "cargo"
args = ["run", "--example=001_engine_init", "--features=gl_dx12"]
dependencies = ["cargo_build-example-001-dx12"]

# --- Release ---
[tasks.release-cargo_build-example-001-dx12]
command = "cargo"
args = ["build", "--example=001_engine_init", "--features=gl_dx12"]

[tasks.release-windows_build-example-001-dx12]
command = "cp"
args = [
    "target/release/examples/001_engine_init.exe",
    "target/release/examples/001_engine_init_dx12.exe",
]
dependencies = ["release-cargo_build-example-001-dx12"]

[tasks.release-non-windows_build-example-001-dx12]
command = "cp"
args = [
    "target/release/examples/001_engine_init",
    "target/release/examples/001_engine_init_dx12",
]
dependencies = ["release-cargo_build-example-001-dx12"]

[tasks.release-build-example-001-dx12]
category = "release-build"
windows_alias = "windows_build-example-001-dx12"
linux_alias = "non-windows_build-example-001-dx12"
mac_alias = "non-windows_build-example-001-dx12"

[tasks.release-run-example-001-dx12]
category = "release-run"
command = "cargo"
args = ["run", "--release", "--example=001_engine_init", "--features=gl_dx12"]
dependencies = ["release-cargo_build-example-001-dx12"]
