# Example 001 - Vulkan
[tasks.cargo_build-example-001-vulkan]
command = "cargo"
args = ["build", "--example=001_engine_init", "--features=gl_vulkan"]

[tasks.windows_build-example-001-vulkan]
command = "cp"
args = [
    "target/debug/examples/001_engine_init.exe",
    "target/debug/examples/001_engine_init_vulkan.exe",
]
dependencies = ["cargo_build-example-001-vulkan"]

[tasks.non-windows_build-example-001-vulkan]
command = "cp"
args = [
    "target/debug/examples/001_engine_init",
    "target/debug/examples/001_engine_init_vulkan",
]
dependencies = ["cargo_build-example-001-vulkan"]

[tasks.build-example-001-vulkan]
category = "build"
windows_alias = "windows_build-example-001-vulkan"
linux_alias = "non-windows_build-example-001-vulkan"
mac_alias = "non-windows_build-example-001-vulkan"

[tasks.run-example-001-vulkan]
category = "run"
command = "cargo"
args = ["run", "--example=001_engine_init", "--features=gl_vulkan"]
dependencies = ["cargo_build-example-001-vulkan"]

# --- Release ---
[tasks.release-cargo_build-example-001-vulkan]
command = "cargo"
args = ["build", "--example=001_engine_init", "--features=gl_vulkan"]

[tasks.release-windows_build-example-001-vulkan]
command = "cp"
args = [
    "target/release/examples/001_engine_init.exe",
    "target/release/examples/001_engine_init_vulkan.exe",
]
dependencies = ["release-cargo_build-example-001-vulkan"]

[tasks.release-non-windows_build-example-001-vulkan]
command = "cp"
args = [
    "target/release/examples/001_engine_init",
    "target/release/examples/001_engine_init_vulkan",
]
dependencies = ["release-cargo_build-example-001-vulkan"]

[tasks.release-build-example-001-vulkan]
category = "release-build"
windows_alias = "windows_build-example-001-vulkan"
linux_alias = "non-windows_build-example-001-vulkan"
mac_alias = "non-windows_build-example-001-vulkan"

[tasks.release-run-example-001-vulkan]
category = "release-run"
command = "cargo"
args = ["run", "--release", "--example=001_engine_init", "--features=gl_vulkan"]
dependencies = ["release-cargo_build-example-001-vulkan"]
