# Examples
extend = [
    { path = "001/001.toml" },
    { path = "002/002.toml" },
    { path = "003/003.toml" },
    { path = "004/004.toml" },
]

[tasks.build-all-examples]
dependencies = [
    "build-example-001-all",
    "build-example-002-all",
    "build-example-003-all",
    "build-example-004-all",
]
category = "build"

[tasks.release-build-all-examples]
dependencies = [
    "release-build-example-001-all",
    "release-build-example-002-all",
    "release-build-example-003-all",
    "release-build-example-004-all",
]
category = "release-build"
