[package]
name = "example_render_server_triangle"
version = "0.1.0"
edition = "2021"

[lib]
name = "app_example_render_server_triangle"
crate-type = ["cdylib", "lib"]

[dependencies]
akimo_runtime = { path = "../../Runtime/" }
