[package]
name = "platform_webassembly"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# Internal
shared = { path = "../../shared" }
# External
wasm-bindgen = "0.2.81"

[dev-dependencies]
wasm-bindgen-test = "0.3"
