# Example 004 - Browser WebGPU
[tasks.cargo_build-example-004-browser_webgpu]
command = "cargo"
args = [
    "build",
    "--example=004_clear_background",
    "--features=gl_browser_webgpu",
]

[tasks.windows_build-example-004-browser_webgpu]
command = "cp"
args = [
    "target/debug/examples/004_clear_background.exe",
    "target/debug/examples/004_clear_background_browser_webgpu.exe",
]
dependencies = ["cargo_build-example-004-browser_webgpu"]

[tasks.non-windows_build-example-004-browser_webgpu]
command = "cp"
args = [
    "target/debug/examples/004_clear_background",
    "target/debug/examples/004_clear_background_browser_webgpu",
]
dependencies = ["cargo_build-example-004-browser_webgpu"]

[tasks.build-example-004-browser_webgpu]
category = "build"
windows_alias = "windows_build-example-004-browser_webgpu"
linux_alias = "non-windows_build-example-004-browser_webgpu"
mac_alias = "non-windows_build-example-004-browser_webgpu"

[tasks.run-example-004-browser_webgpu]
category = "run"
command = "cargo"
args = ["run", "--example=004_clear_background", "--features=gl_browser_webgpu"]
dependencies = ["cargo_build-example-004-browser_webgpu"]

# --- Release ---
[tasks.release-cargo_build-example-004-browser_webgpu]
command = "cargo"
args = [
    "build",
    "--example=004_clear_background",
    "--features=gl_browser_webgpu",
]

[tasks.release-windows_build-example-004-browser_webgpu]
command = "cp"
args = [
    "target/release/examples/004_clear_background.exe",
    "target/release/examples/004_clear_background_browser_webgpu.exe",
]
dependencies = ["release-cargo_build-example-004-browser_webgpu"]

[tasks.release-non-windows_build-example-004-browser_webgpu]
command = "cp"
args = [
    "target/release/examples/004_clear_background",
    "target/release/examples/004_clear_background_browser_webgpu",
]
dependencies = ["release-cargo_build-example-004-browser_webgpu"]

[tasks.release-build-example-004-browser_webgpu]
category = "release-build"
windows_alias = "windows_build-example-004-browser_webgpu"
linux_alias = "non-windows_build-example-004-browser_webgpu"
mac_alias = "non-windows_build-example-004-browser_webgpu"

[tasks.release-run-example-004-browser_webgpu]
category = "release-run"
command = "cargo"
args = [
    "run",
    "--release",
    "--example=004_clear_background",
    "--features=gl_browser_webgpu",
]
dependencies = ["release-cargo_build-example-004-browser_webgpu"]
