# Example 004 - DX12
[tasks.cargo_build-example-004-dx12]
command = "cargo"
args = ["build", "--example=004_clear_background", "--features=gl_dx12"]

[tasks.windows_build-example-004-dx12]
command = "cp"
args = [
    "target/debug/examples/004_clear_background.exe",
    "target/debug/examples/004_clear_background_dx12.exe",
]
dependencies = ["cargo_build-example-004-dx12"]

[tasks.non-windows_build-example-004-dx12]
command = "cp"
args = [
    "target/debug/examples/004_clear_background",
    "target/debug/examples/004_clear_background_dx12",
]
dependencies = ["cargo_build-example-004-dx12"]

[tasks.build-example-004-dx12]
category = "build"
windows_alias = "windows_build-example-004-dx12"
linux_alias = "non-windows_build-example-004-dx12"
mac_alias = "non-windows_build-example-004-dx12"

[tasks.run-example-004-dx12]
category = "run"
command = "cargo"
args = ["run", "--example=004_clear_background", "--features=gl_dx12"]
dependencies = ["cargo_build-example-004-dx12"]

# --- Release ---
[tasks.release-cargo_build-example-004-dx12]
command = "cargo"
args = ["build", "--example=004_clear_background", "--features=gl_dx12"]

[tasks.release-windows_build-example-004-dx12]
command = "cp"
args = [
    "target/release/examples/004_clear_background.exe",
    "target/release/examples/004_clear_background_dx12.exe",
]
dependencies = ["release-cargo_build-example-004-dx12"]

[tasks.release-non-windows_build-example-004-dx12]
command = "cp"
args = [
    "target/release/examples/004_clear_background",
    "target/release/examples/004_clear_background_dx12",
]
dependencies = ["release-cargo_build-example-004-dx12"]

[tasks.release-build-example-004-dx12]
category = "release-build"
windows_alias = "windows_build-example-004-dx12"
linux_alias = "non-windows_build-example-004-dx12"
mac_alias = "non-windows_build-example-004-dx12"

[tasks.release-run-example-004-dx12]
category = "release-run"
command = "cargo"
args = [
    "run",
    "--release",
    "--example=004_clear_background",
    "--features=gl_dx12",
]
dependencies = ["release-cargo_build-example-004-dx12"]
