# Example 004 - Metal
[tasks.cargo_build-example-004-metal]
command = "cargo"
args = ["build", "--example=004_clear_background", "--features=gl_metal"]

[tasks.windows_build-example-004-metal]
command = "cp"
args = [
    "target/debug/examples/004_clear_background.exe",
    "target/debug/examples/004_clear_background_metal.exe",
]
dependencies = ["cargo_build-example-004-metal"]

[tasks.non-windows_build-example-004-metal]
command = "cp"
args = [
    "target/debug/examples/004_clear_background",
    "target/debug/examples/004_clear_background_metal",
]
dependencies = ["cargo_build-example-004-metal"]

[tasks.build-example-004-metal]
category = "build"
windows_alias = "windows_build-example-004-metal"
linux_alias = "non-windows_build-example-004-metal"
mac_alias = "non-windows_build-example-004-metal"

[tasks.run-example-004-metal]
category = "run"
command = "cargo"
args = ["run", "--example=004_clear_background", "--features=gl_metal"]
dependencies = ["cargo_build-example-004-metal"]

# --- Release ---
[tasks.release-cargo_build-example-004-metal]
command = "cargo"
args = ["build", "--example=004_clear_background", "--features=gl_metal"]

[tasks.release-windows_build-example-004-metal]
command = "cp"
args = [
    "target/release/examples/004_clear_background.exe",
    "target/release/examples/004_clear_background_metal.exe",
]
dependencies = ["release-cargo_build-example-004-metal"]

[tasks.release-non-windows_build-example-004-metal]
command = "cp"
args = [
    "target/release/examples/004_clear_background",
    "target/release/examples/004_clear_background_metal",
]
dependencies = ["release-cargo_build-example-004-metal"]

[tasks.release-build-example-004-metal]
category = "release-build"
windows_alias = "windows_build-example-004-metal"
linux_alias = "non-windows_build-example-004-metal"
mac_alias = "non-windows_build-example-004-metal"

[tasks.release-run-example-004-metal]
category = "release-run"
command = "cargo"
args = [
    "run",
    "--release",
    "--example=004_clear_background",
    "--features=gl_metal",
]
dependencies = ["release-cargo_build-example-004-metal"]
