# Example 004 - OpenGL
[tasks.cargo_build-example-004-opengl]
command = "cargo"
args = ["build", "--example=004_clear_background", "--features=gl_opengl"]

[tasks.windows_build-example-004-opengl]
command = "cp"
args = [
    "target/debug/examples/004_clear_background.exe",
    "target/debug/examples/004_clear_background_opengl.exe",
]
dependencies = ["cargo_build-example-004-opengl"]

[tasks.non-windows_build-example-004-opengl]
command = "cp"
args = [
    "target/debug/examples/004_clear_background",
    "target/debug/examples/004_clear_background_opengl",
]
dependencies = ["cargo_build-example-004-opengl"]

[tasks.build-example-004-opengl]
category = "build"
windows_alias = "windows_build-example-004-opengl"
linux_alias = "non-windows_build-example-004-opengl"
mac_alias = "non-windows_build-example-004-opengl"

[tasks.run-example-004-opengl]
category = "run"
command = "cargo"
args = ["run", "--example=004_clear_background", "--features=gl_opengl"]
dependencies = ["cargo_build-example-004-opengl"]

# --- Release ---
[tasks.release-cargo_build-example-004-opengl]
command = "cargo"
args = ["build", "--example=004_clear_background", "--features=gl_opengl"]

[tasks.release-windows_build-example-004-opengl]
command = "cp"
args = [
    "target/release/examples/004_clear_background.exe",
    "target/release/examples/004_clear_background_opengl.exe",
]
dependencies = ["release-cargo_build-example-004-opengl"]

[tasks.release-non-windows_build-example-004-opengl]
command = "cp"
args = [
    "target/release/examples/004_clear_background",
    "target/release/examples/004_clear_background_opengl",
]
dependencies = ["release-cargo_build-example-004-opengl"]

[tasks.release-build-example-004-opengl]
category = "release-build"
windows_alias = "windows_build-example-004-opengl"
linux_alias = "non-windows_build-example-004-opengl"
mac_alias = "non-windows_build-example-004-opengl"

[tasks.release-run-example-004-opengl]
category = "release-run"
command = "cargo"
args = [
    "run",
    "--release",
    "--example=004_clear_background",
    "--features=gl_opengl",
]
dependencies = ["release-cargo_build-example-004-opengl"]
