# Example 004 - Vulkan
[tasks.cargo_build-example-004-vulkan]
command = "cargo"
args = ["build", "--example=004_clear_background", "--features=gl_vulkan"]

[tasks.windows_build-example-004-vulkan]
command = "cp"
args = [
    "target/debug/examples/004_clear_background.exe",
    "target/debug/examples/004_clear_background_vulkan.exe",
]
dependencies = ["cargo_build-example-004-vulkan"]

[tasks.non-windows_build-example-004-vulkan]
command = "cp"
args = [
    "target/debug/examples/004_clear_background",
    "target/debug/examples/004_clear_background_vulkan",
]
dependencies = ["cargo_build-example-004-vulkan"]

[tasks.build-example-004-vulkan]
category = "build"
windows_alias = "windows_build-example-004-vulkan"
linux_alias = "non-windows_build-example-004-vulkan"
mac_alias = "non-windows_build-example-004-vulkan"

[tasks.run-example-004-vulkan]
category = "run"
command = "cargo"
args = ["run", "--example=004_clear_background", "--features=gl_vulkan"]
dependencies = ["cargo_build-example-004-vulkan"]

# --- Release ---
[tasks.release-cargo_build-example-004-vulkan]
command = "cargo"
args = ["build", "--example=004_clear_background", "--features=gl_vulkan"]

[tasks.release-windows_build-example-004-vulkan]
command = "cp"
args = [
    "target/release/examples/004_clear_background.exe",
    "target/release/examples/004_clear_background_vulkan.exe",
]
dependencies = ["release-cargo_build-example-004-vulkan"]

[tasks.release-non-windows_build-example-004-vulkan]
command = "cp"
args = [
    "target/release/examples/004_clear_background",
    "target/release/examples/004_clear_background_vulkan",
]
dependencies = ["release-cargo_build-example-004-vulkan"]

[tasks.release-build-example-004-vulkan]
category = "release-build"
windows_alias = "windows_build-example-004-vulkan"
linux_alias = "non-windows_build-example-004-vulkan"
mac_alias = "non-windows_build-example-004-vulkan"

[tasks.release-run-example-004-vulkan]
category = "release-run"
command = "cargo"
args = [
    "run",
    "--release",
    "--example=004_clear_background",
    "--features=gl_vulkan",
]
dependencies = ["release-cargo_build-example-004-vulkan"]
