[package]
name = "example_render_server_pbr"
version = "0.1.0"
edition = "2021"

[lib]
name = "app_example_render_server_pbr"
crate-type = ["cdylib", "lib"]

[dependencies]
akimo_runtime = { path = "../../Runtime/" }
image = "0.25.1"
