name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_matrix:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

  build:
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust on Windows 
      if: ${{ matrix.os }} == windows-latest
      run: Invoke-WebRequest https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe -OutFile rustup-init.exe; ./rustup-init.exe --default-toolchain stable --profile full -y
    - name: Install Rust on UNIX (Linux & macOS)
      if: ${{ matrix.os }} != windows-latest
      run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --profile full -y

    - name: Install cargo-xcodebuild
      run: cargo install cargo-xcodebuild

    - name: Check
      run: cargo xcodebuild check --verbose --package platform_ios
    - name: Build
      run: cargo xcodebuild build --verbose --package platform_ios
    - name: Run tests
      run: cargo xcodebuild test --verbose --package platform_ios
