# Build Library
[tasks.build-vulkan]
command = "cargo"
args = ["build", "--features=gl_vulkan"]
category = "build"

[tasks.build-metal]
command = "cargo"
args = ["build", "--features=gl_metal"]
category = "build"

[tasks.build-dx12]
command = "cargo"
args = ["build", "--features=gl_dx12"]
category = "build"

[tasks.build-dx11]
command = "cargo"
args = ["build", "--features=gl_dx11"]
category = "build"

[tasks.build-opengl]
command = "cargo"
args = ["build", "--features=gl_opengl"]
category = "build"

[tasks.build-browser_webgpu]
command = "cargo"
args = ["build", "--features=gl_browser_webgpu"]
category = "build"

# --- Release ---
[tasks.release-build-vulkan]
command = "cargo"
args = ["build", "--release", "--features=gl_vulkan"]
category = "release-build"

[tasks.release-build-metal]
command = "cargo"
args = ["build", "--release", "--features=gl_metal"]
category = "release-build"

[tasks.release-build-dx12]
command = "cargo"
args = ["build", "--release", "--features=gl_dx12"]
category = "release-build"

[tasks.release-build-dx11]
command = "cargo"
args = ["build", "--release", "--features=gl_dx11"]
category = "release-build"

[tasks.release-build-opengl]
command = "cargo"
args = ["build", "--release", "--features=gl_opengl"]
category = "release-build"

[tasks.release-build-browser_webgpu]
command = "cargo"
args = ["build", "--release", "--features=gl_browser_webgpu"]
category = "release-build"
