# Example 003 - Browser WebGPU
[tasks.cargo_build-example-003-browser_webgpu]
command = "cargo"
args = [
    "build",
    "--example=003_window_fps_counter",
    "--features=gl_browser_webgpu",
]

[tasks.windows_build-example-003-browser_webgpu]
command = "cp"
args = [
    "target/debug/examples/003_window_fps_counter.exe",
    "target/debug/examples/003_window_fps_counter_browser_webgpu.exe",
]
dependencies = ["cargo_build-example-003-browser_webgpu"]

[tasks.non-windows_build-example-003-browser_webgpu]
command = "cp"
args = [
    "target/debug/examples/003_window_fps_counter",
    "target/debug/examples/003_window_fps_counter_browser_webgpu",
]
dependencies = ["cargo_build-example-003-browser_webgpu"]

[tasks.build-example-003-browser_webgpu]
category = "build"
windows_alias = "windows_build-example-003-browser_webgpu"
linux_alias = "non-windows_build-example-003-browser_webgpu"
mac_alias = "non-windows_build-example-003-browser_webgpu"

[tasks.run-example-003-browser_webgpu]
category = "run"
command = "cargo"
args = [
    "run",
    "--example=003_window_fps_counter",
    "--features=gl_browser_webgpu",
]
dependencies = ["cargo_build-example-003-browser_webgpu"]

# --- Release ---
[tasks.release-cargo_build-example-003-browser_webgpu]
command = "cargo"
args = [
    "build",
    "--example=003_window_fps_counter",
    "--features=gl_browser_webgpu",
]

[tasks.release-windows_build-example-003-browser_webgpu]
command = "cp"
args = [
    "target/release/examples/003_window_fps_counter.exe",
    "target/release/examples/003_window_fps_counter_browser_webgpu.exe",
]
dependencies = ["release-cargo_build-example-003-browser_webgpu"]

[tasks.release-non-windows_build-example-003-browser_webgpu]
command = "cp"
args = [
    "target/release/examples/003_window_fps_counter",
    "target/release/examples/003_window_fps_counter_browser_webgpu",
]
dependencies = ["release-cargo_build-example-003-browser_webgpu"]

[tasks.release-build-example-003-browser_webgpu]
category = "release-build"
windows_alias = "windows_build-example-003-browser_webgpu"
linux_alias = "non-windows_build-example-003-browser_webgpu"
mac_alias = "non-windows_build-example-003-browser_webgpu"

[tasks.release-run-example-003-browser_webgpu]
category = "release-run"
command = "cargo"
args = [
    "run",
    "--release",
    "--example=003_window_fps_counter",
    "--features=gl_browser_webgpu",
]
dependencies = ["release-cargo_build-example-003-browser_webgpu"]
