# Example 003 - OpenGL
[tasks.cargo_build-example-003-opengl]
command = "cargo"
args = ["build", "--example=003_window_fps_counter", "--features=gl_opengl"]

[tasks.windows_build-example-003-opengl]
command = "cp"
args = [
    "target/debug/examples/003_window_fps_counter.exe",
    "target/debug/examples/003_window_fps_counter_opengl.exe",
]
dependencies = ["cargo_build-example-003-opengl"]

[tasks.non-windows_build-example-003-opengl]
command = "cp"
args = [
    "target/debug/examples/003_window_fps_counter",
    "target/debug/examples/003_window_fps_counter_opengl",
]
dependencies = ["cargo_build-example-003-opengl"]

[tasks.build-example-003-opengl]
category = "build"
windows_alias = "windows_build-example-003-opengl"
linux_alias = "non-windows_build-example-003-opengl"
mac_alias = "non-windows_build-example-003-opengl"

[tasks.run-example-003-opengl]
category = "run"
command = "cargo"
args = ["run", "--example=003_window_fps_counter", "--features=gl_opengl"]
dependencies = ["cargo_build-example-003-opengl"]

# --- Release ---
[tasks.release-cargo_build-example-003-opengl]
command = "cargo"
args = ["build", "--example=003_window_fps_counter", "--features=gl_opengl"]

[tasks.release-windows_build-example-003-opengl]
command = "cp"
args = [
    "target/release/examples/003_window_fps_counter.exe",
    "target/release/examples/003_window_fps_counter_opengl.exe",
]
dependencies = ["release-cargo_build-example-003-opengl"]

[tasks.release-non-windows_build-example-003-opengl]
command = "cp"
args = [
    "target/release/examples/003_window_fps_counter",
    "target/release/examples/003_window_fps_counter_opengl",
]
dependencies = ["release-cargo_build-example-003-opengl"]

[tasks.release-build-example-003-opengl]
category = "release-build"
windows_alias = "windows_build-example-003-opengl"
linux_alias = "non-windows_build-example-003-opengl"
mac_alias = "non-windows_build-example-003-opengl"

[tasks.release-run-example-003-opengl]
category = "release-run"
command = "cargo"
args = [
    "run",
    "--release",
    "--example=003_window_fps_counter",
    "--features=gl_opengl",
]
dependencies = ["release-cargo_build-example-003-opengl"]
