name: GitLab Mirror

on:
  push:
    branches: [ "**" ]

jobs:
  gitlab_mirror:
    runs-on: ubuntu-latest

    steps:
    # Download a mirror and push it to GitLab
    - run: |
        git clone https://github.com/rust-multiplatform/Base-Project-Template mirror_repo
        cd mirror_repo
        git fetch --all
        git remote add gitlab https://sakul6499:$GITLAB_TOKEN@gitlab.com/rust-multiplatform/base-project-template.git
        git push gitlab --all
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
