name: GitLab Mirror

on:
  push:
    branches: [ "**" ]

env:
  GITLAB_MIRROR_KEY: ${{ secrets.GITLAB_MIRROR }}

jobs:
  gitlab_mirror:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Fetch all
    - run: git fetch --all

    # Setup SSH
    - run: mkdir ~/.ssh/
    - run: echo "$GITLAB_MIRROR_KEY" | tee ~/.ssh/id_rsa
    - run: cat ~/.ssh/id_rsa
    - run: git config --global user.name "Lukas Weber"
    - run: git config --global user.email "me@sakul6499.de"

    # Setup Mirror
    - run: git remote set-url origin git@gitlab.com:rust-multiplatform/base-project-template.git

    # Push to Mirror
    - run: GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa' git push origin --all
