name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  platform_linux:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --profile minimal -y

    - name: Check
      run: cargo check --verbose --package platform_linux
    - name: Build
      run: cargo build --verbose --package platform_linux
    - name: Run tests
      run: cargo test --verbose --package platform_linux

    - uses: actions/upload-artifact@v3
      with:
        name: platform_linux
        path: target/
