name: Platform Android

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  platform_android:
    strategy:
      matrix:
        os: [ubuntu-latest]
        # No target needed here.
        # xcodebuild automatically builds for all architectures and compresses them into one APP
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --profile minimal -y

    - name: Install target x86_64-linux-android
      run: rustup target add x86_64-linux-android
    - name: Install target aarch64-linux-android
      run: rustup target add aarch64-linux-android
    - name: Install target i686-linux-android
      run: rustup target add i686-linux-android
    - name: Install target armv7-linux-androideabi
      run: rustup target add armv7-linux-androideabi

    - name: Install cargo-apk
      run: cargo install cargo-apk

    - name: Check
      run: cargo apk check --verbose --package platform_android
    - name: Build (Debug)
      run: cargo apk build --verbose --package platform_android
    - name: Build (Release)
      run: cargo apk build --verbose --package platform_android --release
    # Testing can't be done on iOS.
    # However, we are testing on the `shared` code and other architectures.

    - uses: actions/upload-artifact@v3
      with:
        name: "platform_android_${{ matrix.target }}_debug"
        path: target/debug/platform_*
    - uses: actions/upload-artifact@v3
      with:
        name: "platform_android_${{ matrix.target }}_release"
        path: target/debug/platform_*
