name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  platform_android:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --profile minimal -y

    - name: Install cargo-apk
      run: cargo install cargo-apk

    - name: Check
      run: cargo apk check --verbose --package platform_android
    - name: Build
      run: cargo apk build --verbose --package platform_android
    - name: Run tests
      run: cargo apk test --verbose --package platform_android

    - uses: actions/upload-artifact@v3
      with:
        name: platform_android
        path: target/
