name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  platform_ios:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --profile complete -y

    - name: Install cargo-xcodebuild
      run: cargo install cargo-xcodebuild

    - name: Check
      run: cargo xcodebuild check --verbose --package platform_ios
    - name: Build
      run: cargo xcodebuild build --verbose --package platform_ios
    - name: Run tests
      run: cargo xcodebuild test --verbose --package platform_ios
