name: Platform WebAssembly

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  platform_webassembly:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3


    - name: Install Rust
      run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --profile minimal -y
    - name: Install WASM-Pack
      run:  curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh 

    - name: Build (Debug)
      run: wasm-pack build platform/webassembly/ --package platform_webassembly
    - name: Run Tests (Debug)
      run: wasm-pack test platform/webassembly/ --package platform_webassembly
    - uses: actions/upload-artifact@v3
      with:
        name: "platform_webassembly_debug"
        path: ./platform/webassembly/pkg
        if-no-files-found: error 


    - name: Build (Release)
      run: wasm-pack build --release platform/webassembly/ --package platform_webassembly
    - name: Run Tests (Release)
      run: wasm-pack test --release platform/webassembly/ --package platform_webassembly
    - uses: actions/upload-artifact@v3
      with:
        name: "platform_webassembly_release"
        path: ./platform/webassembly/pkg
        if-no-files-found: error 
