name: Platform Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  platform_linux:
    strategy:
      matrix:
        os: [ubuntu-latest]
        target: [aarch64-unknown-linux-gnu, i686-unknown-linux-gnu, x86_64-unknown-linux-gnu, aarch64-unknown-linux-musl, arm-linux-androideabi, arm-unknown-linux-gnueabi, arm-unknown-linux-gnueabihf, arm-unknown-linux-musleabi, arm-unknown-linux-musleabihf, armv5te-unknown-linux-gnueabi, armv7-linux-androideabi, armv7-unknown-linux-gnueabihf, armv7-unknown-linux-musleabihf, i586-unknown-linux-gnu, i586-unknown-linux-musl, i686-unknown-linux-musl, mips-unknown-linux-gnu, mips-unknown-linux-musl, mips64-unknown-linux-gnuabi64, mips64el-unknown-linux-gnuabi64, mipsel-unknown-linux-gnu, mipsel-unknown-linux-musl, powerpc-unknown-linux-gnu, powerpc64-unknown-linux-gnu, powerpc64le-unknown-linux-gnu, s390x-unknown-linux-gnu, sparc64-unknown-linux-gnu, x86_64-unknown-linux-gnux32, x86_64-unknown-linux-musl]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --profile minimal -y

    - name: Install target ${{ matrix.target }}
      run: rustup target add ${{ matrix.target }}

    - name: Check
      run: cargo check --verbose --package platform_linux
    - name: Build (Debug)
      run: cargo build --verbose --package platform_linux
    - name: Build (Release)
      run: cargo build --verbose --package platform_linux --release
    - name: Run Tests (Debug)
      if: ${{ matrix.target == 'x86_64-unknown-linux-gnu' }} # Testing can only be done on the host architecture. It should work across all architectures though!
      run: cargo test --verbose --package platform_linux
    - name: Run Tests (Release)
      if: ${{ matrix.target == 'x86_64-unknown-linux-gnu' }} # Testing can only be done on the host architecture. It should work across all architectures though!
      run: cargo test --verbose --package platform_linux --release

    - name: List target/ Files
      run: ls -al target/*

    - uses: actions/upload-artifact@v3
      with:
        name: platform_linux
        path: target/
