name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  platform_ios:
    strategy:
      matrix:
        os: [macos-latest]
        target: [x86_64-apple-ios, aarch64-apple-ios, aarch64-apple-ios-sim]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --profile minimal -y

    - name: Install target ${{ matrix.target }}
      run: rustup target add ${{ matrix.target }}

    - name: Install cargo-xcodebuild
      run: cargo install cargo-xcodebuild

    - name: Check
      run: cargo xcodebuild check --verbose --package platform_ios --target ${{ matrix.target }}
    - name: Build
      run: cargo xcodebuild build --verbose --package platform_ios --target ${{ matrix.target }}
    # Testing can't be done on iOS.
    # However, we are testing on the `shared` code and other architectures.

    - uses: actions/upload-artifact@v3
      with:
        name: platform_ios
        path: target/
