name: Trigger Merger

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Merger-CI workflow 
        run: |
          curl -XPOST -u "${{ secrets.TRIGGER_CREDENTIALS }}" -H "Accept:application/vnd.github" -H "Content-Type:application/json" https://api.github.com/repos/rust-multiplatform/CI-Merger/dispatches --data '{"ref": "main" }'
