name: Trigger Merger

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Merger-CI workflow 
        run: |
          curl -L -X POST -H "Accept:application/vnd.github" -H "Authorization: Bearer ${{ secrets.TRIGGER_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/rust-multiplatform/CI-Merger/dispatches -d '{"event_type":"upstream-trigger","client_payload":{"ci":true}}'
