name: Trigger Merger

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Merger-CI workflow 
        run: |
          curl --fail-with-body -L -X POST -u "${{ secrets.TRIGGER_CREDENTIALS }}" -H "Accept:application/vnd.github" https://api.github.com/repos/rust-multiplatform/CI-Merger/dispatches -d '{"event_type":"upstream-trigger","client_payload":{"ci":true}}'
